# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d89b3637e9061fe44ca71140adcd11740a9a0c8bd0eb110eecbbfd8ff040ffc12e14bb9c8a172de278523144448016ef1b088d5f1acb8825077e5e8965d59b8

test:
  secret_key_base: 624ee6705f52c9b55a54d4fd68190dc87a6364b5f3438f20cd3b9e033dd59995bb522161d26df8bc72cdd935be3557dd5598952d86fe4e05be2b48f4deb35a0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
